name: Trigger Action to run check update data python script

on:
  schedule:
    - cron: '0 22 * * *' # every 10th and 20th of each month
  workflow_dispatch:
    

jobs:
  run-python-check-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install a specific version of uv
      uses: astral-sh/setup-uv@v5
      with:
        version: ">=0.4.0"

    - name: Install dependencies
      run: uv sync 

    - name: run action test
      run: uv run pyscript.py 
