name: Trigger Action to run check update data python script

on:
  schedule:
    - cron: '*/1 * * * *' # every 10th and 20th of each month
  workflow_dispatch:
    

jobs:
  run-python-check-update:
    runs-on: ubuntu-latest

    steps:
      - name: run action test
        run: echo "hello"
